### ISSUE TITLE
DNSSEC doesn't provide consistency

### ISSUE THREAD

**Issue by martinthomson** [tfpauly/draft-ohai-svcb-config#11]
> One mitigation specific to this mechanism is validating that SVCB or HTTPS records including the "oblivious-configs" are protected by [DNSSEC](https://www.ietf.org/archive/id/draft-pauly-ohai-svcb-config-00.html#DNSSEC) [DNSSEC]. This prevents attacks where a unique response is generated for each client of a resolver.

-- https://www.ietf.org/archive/id/draft-pauly-ohai-svcb-config-00.html#section-5-3

This isn't true as DNSSEC responses can be customized on a per-client basis (worse if EDNS(0) client subnet is in use).  What might be a more realistic protection here is caching at a resolver, which might prevent that sort of customization.  Of course, if this is for DNS resolution - as it is - that doesn't necessarily help that much.

**Comment by tfpauly** [comment]
Fair enough — we can remove this comment.

**Comment by tfpauly** [comment]
This was removed a while ago
