### ISSUE TITLE
What does ohttp-path identify?

### ISSUE THREAD

**Issue by martinthomson** [tfpauly/draft-ohai-svcb-config#12]
Is it the oblivious request resource or the oblivious proxy resource.  Clients need the latter, but it doesn't seem like you have allowed for an absolute URI as this is a "path" and not a URI and [this](https://www.ietf.org/archive/id/draft-pauly-ohai-svcb-config-00.html#section-3-4) says:

> If this path parameter is not present, oblivious requests can be made to the root "/" path.

... on which server?

**Comment by tfpauly** [comment]
This is meant to be the path on the target server, not the proxy. The client would need to work with the proxy to know how the target maps to a request.

The entity publishing the target config only knows about the target name and path, not the proxy info. Knowing how a proxy does mappings is out of scope here, I think.

**Comment by tfpauly** [comment]
FYI @chris-wood , since you had asked for the path parameter to be added.

**Comment by martinthomson** [comment]
New version out, this appears OBE.
