### ISSUE TITLE
A client has to trust the oblivious proxy resource

### ISSUE THREAD

**Issue by martinthomson** [tfpauly/draft-ohai-svcb-config#13]
If it gets this via a discovery process, how does it know that it can trust that resource?

**Comment by tfpauly** [comment]
In this model, the client isn't discovering the proxy — it's discovering the target, and has a proxy that it trusts already. Proxy discovery would be a separate mechanism.

**Comment by martinthomson** [comment]
I see.  That wasn't at all clear.  OHTTP doesn't really let you choose a target at the proxy though, so how would you propose that the client discover the oblivious proxy resource?

**Comment by tfpauly** [comment]
The client would be using a proxy it already knows about or knows can handle this target.

**Comment by tfpauly** [comment]
Text has since clarified that this doesn't cover discovery of the proxy / relay. We can have further discussion if people think it's needed (beyond having client-selected/trusted relays).
