### ISSUE TITLE
OHTTP targets need a path

### ISSUE THREAD

**Issue by chris-wood** [tfpauly/draft-ohai-svcb-config#2]
I may have missed it, but the current draft doesn't seem to provide a way for clients to discover the full oblivious target resource from a HTTPS record with the "oblivious-configs" parameter -- it only gives them the configuration structure. Similar to the DNS case, OHTTP targets are defined by their path, so I think it might make sense to mint a new parameter for the path, maybe "oblivious-path"?

**Comment by tfpauly** [comment]
Yeah, for the DNS case, they have dohpath, but I think we'd need a path here too for oblivious HTTP generically!

**Comment by chris-wood** [comment]
@tfpauly would you like a PR?

**Comment by tfpauly** [comment]
Nah, I can add it soon.
