### ISSUE TITLE
Unique DoH path attack

### ISSUE THREAD

**Issue by tireddy2** [tfpauly/draft-ohai-svcb-config#26]
Some options include: only allow common DoH paths (such as the de-facto default "/dns-query{?dns}");
performing consistency checks by fetching the information about the resolver over multiple resolution paths; or coordinating with a
trusted oblivious relay to validate that DoH paths are common across clients using the same gateway.

Comment> The consistency check discussed above in security considerations section is not clear to me. For example, in case of DNR, the client will use DHCP/RA to learn the DoH path and it can use discovered ADN or Do53 to do the the SVCB lookup to cross-check both DoH paths are matching. 

I don't get how the client will co-ordinate with a oblivious relay to validate that DoH path. Is the client supposed to use the de-facto URI path to retrieve the actual URI path from the Oblivious DoH service.

**Comment by tfpauly** [comment]
I was thinking that either you would:
- Check that the path in the SVCB response is the same if you look it up locally and publicly (two resolvers)
- Have some proprietary method to reveal what the interior DoH path is to the relay, and the relay can reject requests to paths that look like targeting.

**Comment by tireddy2** [comment]
I like the first approach compared to the proprietary method :)

**Comment by tireddy2** [comment]
I see draft-schwartz-ohai-consistency-doublecheck solves the problem by including the DoH path in the service description host.

**Comment by tfpauly** [comment]
Yeah, that works if you have some such dictionary file.

**Comment by tireddy2** [comment]
we may want to consider using a separate section to list the possible remediation mechanisms to detect unique DoH path attack.
