### ISSUE TITLE
Mixed configuration structures for DNS

### ISSUE THREAD

**Issue by chris-wood** [tfpauly/draft-ohai-svcb-config#3]
The draft currently allows for the "configs" parameter to carry an `ObliviousDoHConfigs` structure instead of a `KeyConfig`. `ObliviousDoHConfigs` looks like so:

~~~
struct {
   uint16 kem_id;
   uint16 kdf_id;
   uint16 aead_id;
   opaque public_key<1..2^16-1>;
} ObliviousDoHConfigContents;

struct {
   uint16 version;
   uint16 length;
   select (ObliviousDoHConfig.version) {
      case 0x0001: ObliviousDoHConfigContents contents;
   }
} ObliviousDoHConfig;

ObliviousDoHConfig ObliviousDoHConfigs<1..2^16-1>;
~~~

And `KeyConfig`:

~~~
struct {
  uint8 key_id;
  HpkeKemId kem_id;
  HpkePublicKey public_key;
  HpkeSymmetricAlgorithms cipher_suites<4..2^16-4>;
} KeyConfig;
~~~

I've not actually worked it out, but I wonder if these structures are defined such that clients can always distinguish between the two. If clients get confused, they might try to engage the OHTTP encapsulation logic instead of ODoH logic (or vice versa), and I don't think we have a good understanding of what can happen as a result.

Absent this analysis, I would drop the ability for configs to carry either one of these structures, and unify around `KeyConfig`.

**Comment by tfpauly** [comment]
I don't think it's possible for a config to parse validly for both — we can add the analysis.

**Comment by chris-wood** [comment]
Having this ambiguous definition doesn't seem particularly helpful. Why not just pick the simpler thing here?

**Comment by tfpauly** [comment]
The simpler thing being defining two separate keys?

**Comment by chris-wood** [comment]
There's probably at least three options:

1. Use separate keys for each config type
1. Use `KeyConfig` for OHTTP and `ObliviousDoHConfigs` for ODoH
1. Use `KeyConfig` for OHTTP and ODoH

I would go with option (3), but (1) and (2) seem reasonable?

**Comment by tfpauly** [comment]
I think the choice is more like:
1. Use one SVCB parameter for `KeyConfig`, which covers OHTTP generic and ODoH "v2", and another SVCB parameter for `ObliviousDoHConfigs` for ODoH "v1"
2. Use the same SVCB parameter for both versions of ODoH, so that DNS resolver software doesn't have to care about the two

**Comment by chris-wood** [comment]
That's a better framing, and between the two, I would go with (1). 🤷

**Comment by chris-wood** [comment]
@tfpauly would you like a PR?

**Comment by tfpauly** [comment]
No, I'll do a restructure.
