### ISSUE TITLE
Key consistency

### ISSUE THREAD

**Issue by chris-wood** [tfpauly/draft-ohai-svcb-config#4]
The security considerations section lists several ways in which clients could try to ensure they have a consistent view of the oblivious target's public key. Shamelessly, I would instead cite [this document](https://chris-wood.github.io/key-consistency/draft-wood-key-consistency.html), as that's what OHTTP is doing now. (We're going to SECDISPATCH this to see what becomes of it.)

**Comment by tfpauly** [comment]
Yes, that's a good citation to make
