### ISSUE TITLE
Gateway location matters for the relay, not the client

### ISSUE THREAD

**Issue by chris-wood** [tfpauly/draft-ohai-svcb-config#42]
> Clients that know a service is available as a target
via discovery through the "ohttp" parameter in a SVCB or HTTPS
record need to know the location of the associated gateway
before sending oblivious requests.

The relay is the one that sends the request to the gateway, so this feels wrong. The client only needs to know the relay location to which its requests should be sent. If the idea is that the client somehow communicates the gateway location to the relay, that would be a deployment-specific feature and not something that OHTTP supports out-of-the-box, and so either (1) that should be clarified as such or (2) the assumptions around how relays know to which endpoint requests are forwarded need to be clarified.

**Comment by tfpauly** [comment]
Yeah, I guess it should be that the client needs to know the key configuration of the gateway and how to request it via the relay.
